### ISSUE TITLE
hdf5 to txt conversion of order_file

### ISSUE THREAD

**Issue by ksandeshk** [drimpossible/BudgetCL#2]
The downloaded dataset ImageNet2K using https://github.com/hammoudhasan/CLDatasets has the order_file(s) in hdf5 format. The dataloader of BudgetCL needs order_file(s) in txt format. hdf5 to txt conversion is needed to run BudgetCL code.

**Comment by ZexinLi0w0** [comment]
Also met this issue. The downloaded datasets  provides order_files containing files with .hdf5 suffix. The dataloader of BudgetCL requires .txt files.

https://github.com/drimpossible/BudgetCL/blob/e27b5485910c7c9460f8896f1fbbdd561bb3b596/src/datasets.py#L46-L60

Also, it seems the downloaded datasets' order_files doesn't simply match as in BudgetCL's code.
```
$ ls ../cl_datasets/ImageNet2K/order_files/
class_inc_image_paths.hdf5  class_inc_labels.hdf5  data_inc_image_paths.hdf5  data_inc_labels.hdf5  pretest_image_paths.hdf5  pretest_labels.hdf5  pretrain_image_paths.hdf5  pretrain_labels.hdf5  preval_image_paths.hdf5  preval_labels.hdf5  test_image_paths.hdf5  test_labels.hdf5  val_image_paths.hdf5  val_labels.hdf5
```
while the BudgetCL's datasets.py seems to require `pretrain.txt`, `preval.txt`, `pretest.txt`, `val.txt` and `test.txt`.

**Comment by ksandeshk** [comment]
Try the below approach -
1) read the hdf5 file
with h5py.File("./val_image_paths.hdf5", 'r') as h5_file:
    val_paths = h5_file['store_list'][()]
2) store val_paths to val.txt

**Comment by ZexinLi0w0** [comment]
> Try the below approach -
> 
> 1. read the hdf5 file
>    with h5py.File("./val_image_paths.hdf5", 'r') as h5_file:
>    val_paths = h5_file['store_list'][()]
> 2. store val_paths to val.txt

Thanks, this resolves the issue.
